fakhrialdariasky/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fakhrialdariaskyapp.urls')),
]

fakhrialdariaskyapp/urls.py
from django.urls import path

from . import views

app_name = 'fakhrialdariaskyapp'

urlpatterns = [
    path('', views.index, name='home'),
    path('home/', views.index, name='index'),
    path('profile/', views.biodata, name='index'),


    path("matkuls/add",views.matkul_add,name="matkul_add"),
    path("matkuls/<int:id>/read",views.matkul_read,name="matkul_read"),
    path("matkuls/<int:id>/delete",views.matkul_delete,name="matkul_delete"),
    path('matkuls/', views.matkul_index, name='matkul_index'),

]

fakhrialdariaskyapp/models.py
from django.db import models
from django.shortcuts import reverse

semesters = [
    ("2019/2020 Gasal","2019/2020 Gasal"),
    ("2019/2020 Genap","2019/2020 Genap"),
    ("2020/2021 Gasal","2020/2021 Gasal"),
    ("2020/2021 Genap","2020/2021 Genap"),
    ("2021/2022 Gasal","2021/2022 Gasal"),
    ("2021/2022 Genap","2021/2022 Genap"),
    ("2022/2023 Gasal","2022/2023 Gasal"),
    ("2022/2023 Genap","2022/2023 Genap")
]

class MataKuliah(models.Model):
    nama = models.TextField(max_length = 100)
    dosen = models.TextField(max_length = 70)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField(max_length = 1000)
    semester = models.TextField(choices = semesters)
    ruangan = models.TextField(max_length = 100)

    def __str__(self):
        return "{} ({})".format(self.nama,self.dosen)

    def get_absolute_url(self):
        return reverse("fakhrialdariaskyapp:matkul_read",args=[self.id])

fakhrialdariaskyapp/forms.py
from django import forms
from .models import MataKuliah

class FormMatkul(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = "__all__"

fakhrialdariaskyapp/views.py
from django.shortcuts import render, redirect
#from django.http import HttpResponse
from datetime import datetime, date
from .models import MataKuliah
from .forms import FormMatkul
from django.contrib import messages

# Enter your name here
mhs_name = 'Yusuf Fakhri Aldrian' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
curr_month = int(datetime.now().strftime("%m"))
curr_day = int(datetime.now().strftime("%d"))
angkatan = 2019
birth_date = date(2002, 12, 28) #TODO Implement this, format (Year, Month, Date)
birth_day_complete = str(birth_date.day) + " " + birth_date.strftime("%B") + " " + str(birth_date.year)
hobby = "Menonton film dan membaca"
npm = 1906351096 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year, birth_date.month, birth_date.day), 'npm': npm, 'hobby': hobby, 'angkatan': angkatan, "birthday": birth_day_complete}
    return render(request, 'main/index_page.html', response)
    
def biodata(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year, birth_date.month, birth_date.day), 'npm': npm, 'hobby': hobby, 'angkatan': angkatan, "birthday": birth_day_complete}
    return render(request, 'main/index_lab1.html', response)

def calculate_age(birth_year, birth_month, birth_day):
    if birth_year > curr_year:
        return 0
    elif curr_month < birth_month:
        return curr_year - birth_year - 1
    elif curr_month == birth_month:
        if curr_day < birth_day:
            return curr_year - birth_year - 1
        return curr_year - birth_year
    else:
        return curr_year - birth_year

def matkul_index(request):
    context = {
        "mata_kuliah_list" : MataKuliah.objects.all().order_by("-id"),
    }
    return render(request, "main/index_story5.html", context)

def matkul_add(request):
    if request.method == "POST":
        matkul_form = FormMatkul(request.POST)
        if matkul_form.is_valid():
            matkul_form.save()
            messages.add_message(request, messages.SUCCESS, "Matkul '{}' Ditambahkan".format(request.POST["nama"]))
        return redirect("/matkuls")
    return render(request,"main/matkul_add.html")

def matkul_read(request,id):
    matkul = MataKuliah.objects.get(id=id)
    context = {
        "mata_kuliah" : matkul,
    }
    return render(request,"main/matkul_read.html", context)

def matkul_delete(request,id):
    if request.method == "POST":
        mata_kuliah = MataKuliah.objects.get(id=id)
        mata_kuliah.delete()
        messages.add_message(request, messages.SUCCESS, "Matkul '{}' Dihapuskan".format(mata_kuliah.nama))
    return redirect("/matkuls")

    

fakhrialdariaskyapp/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

fakhrialdariaskyapp/templates/main/index_lab1.html
{% extends 'base.html' %} {% block content %}

<img src="https://maung.id/static/5ea17d7a15e02cbcd5626d4df05b4c85/9f583/FR54.jpg" width="189" height="280" class="rounded float-right">

<h1>
    Hi! Nama aku {{name}}
    <a href="{{name}}/edit"><i class="fal fa-edit fa-xs"></i></a>
</h1>

<p class="lead">NPM: <i class="fa fa-table"></i> {{npm}} </p>

<p class="lead">Ulang tahun: <i class="fa fa-calendar-exclamation"></i> {{birthday}}</p>

<p class="lead">Umur: <i class="fa fa-birthday-cake"></i> {{age}} tahun</p>

<p class="lead">Hobi: <i class="fa fa-volleyball-ball"></i> {{hobby}}</p>

<p class="lead">Kuliah: <i class="fa fa-university"></i> Fakultas Ilmu Komputer, Universitas Indonesia</p>

<p class="lead">Angkatan: <i class="fa fa-equals"></i> {{angkatan}}</p>

<p class="lead">Riwayat pendidikan: <i class="fa fa-equals"></i> </p>
<ul class="list-group list-group-flush">
    <li class="list-group-item">SD Dian Didaktika (2008-2014) <img src="https://pbs.twimg.com/profile_images/2732008449/ceb66693d30ba2967a01e3ed6b0e0266_400x400.png" width="189" height="189" class="rounded float-right"></li>
    <li class="list-group-item">SMP Labschool Kebayoran (2016-2019)<img src="https://upload.wikimedia.org/wikipedia/id/9/93/Logo_Labschool.png" width="189" height="189" class="rounded float-right"></li>
    <li class="list-group-item">SMA Labschool Kebayoran (2014-2016)<img src="https://upload.wikimedia.org/wikipedia/id/9/93/Logo_Labschool.png" width="189" height="189" class="rounded float-right"></li>
    <li class="list-group-item">Fakultas Ilmu Komputer, Universitas Indonesia (2019-)<img src="https://acakadul.files.wordpress.com/2013/08/makara-ui-fasilkom.png" width="189" height="189" class="rounded float-right"></li>
</ul>

<br>

<a class="btn btn-primary float-right" href="https://www.linkedin.com/in/ysfakhrialdrian/" target="_blank " role="button ">
    <i class="fab fa-linkedin-in"></i>
</a>
<a class="btn btn-secondary float-right" href="https://www.instagram.com/fakhrialdrn/" target="_blank " role="button ">
    <i class="fab fa-instagram"></i> fakhrialdrn
</a>
<a class="btn btn-success float-right disabled" href="" role="button ">
    <i class="fab fa-line"></i> aldrianyf
</a>

<br><br><br>
<blockquote class="blockquote">
    <p class="mb-0">
        Halo! Namaku Yusuf Fakhri Aldrian. Saya adalah orang yang ambisius. Meski begitu saya juga orang yang selow, tidak terlalu tertekan dan enak dalam pergaulan.
    </p>
    <footer class="blockquote-footer">Biografi</footer>
</blockquote>

<p class="mt-5 mb-3 text-muted ">© 2020 Yusuf Fakhri Aldrian</p>
</div>
</div>
<br><br> {% endblock %}

fakhrialdariaskyapp/templates/main/index_page.html
{% extends 'base.html' %} {% block content %}



<div class="text-center">
    <img src="https://maung.id/static/5ea17d7a15e02cbcd5626d4df05b4c85/9f583/FR54.jpg" width="189" height="280" class="rounded float-center">
    <h5> Halo! </h5>
    <h5> Ini website Yusuf Fakhri Aldrian </h5>
    <p> Seorang pembelajar programming dari Fasilkom UI </p>
    <p class="lead"> Salam kenal! </p>
    <a class="btn btn-success" href="/profile" role="button ">
        <i class="fas fa-user"></i> Lihat profil (Story 1)
    </a>
    <br><br>
    <a class="btn btn-info" href="/matkuls" role="button ">
        <i class="fas fa-books"></i> Ke laman mata kuliah (Story 5)
    </a>
</div>

</div>
</div>
<br><br> {% endblock %}

fakhrialdariaskyapp/templates/main/index_story5.html
{% extends 'base.html' %} {% block content %} {% if messages %} {% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
</div>
{% endfor %} {% endif %} {% for mata_kuliah in mata_kuliah_list %}
<div class="card text-white bg-success mt-2 mb-2 mx-auto" style="max-width: 50rem;">
    <div class="card-header d-flex justify-content-between">
        <h5 class="my-auto"> {{mata_kuliah.nama}} </h5>
        <div class="d-flex flex-row">
            <a href={{mata_kuliah.get_absolute_url}} class="btn btn-danger mx-1 my-auto">Detail</a>
            <form action="{% url 'fakhrialdariaskyapp:matkul_delete' mata_kuliah.id %}" class="my-auto" method="POST">
                {% csrf_token %}
                <button class="btn btn-primary mx-1" type="input">Delete</button>
            </form>
        </div>
    </div>
    <div class="card-body">
        <p class="card-text m-1">Ruangan: {{mata_kuliah.ruangan}} </p>
        <p class="card-text m-1">Dibawa Oleh {{mata_kuliah.dosen}} </p>
    </div>
</div>
{% endfor %}
<a class="btn btn-info" href="/matkuls/add" role="button ">
    <i class="fas fa-books"></i> Tambah matkul
</a>
{% endblock %}

fakhrialdariaskyapp/templates/main/matkul_add.html
{% extends 'base.html' %} {% block content %}
<form method="POST" action="/matkuls/add">
    {% csrf_token %}
    <div class="card text-dark bg-light mt-1 mb-3 mx-auto" style="max-width: 50rem;">
        <div class="card-header d-flex justify-content-between">
            <div class="d-flex flex-column">
                <h5 class="my-auto"><input class="form-control-lg col-9 mb-3 p-0" placeholder="Nama mata kuliah" name="nama" required></h5>
                <p class="card-text m-1 mt-2">Ruangan: <input class="form-control-sm w-75 ml-1" placeholder="Kode Ruangan" name="ruangan" required></p>
                <p class="card-text m-1">Dibawa Oleh <input class="form-control-sm w-75 ml-1" placeholder="Nama dosen" name="dosen" required></p>
            </div>
            <div class="d-flex flex-column">
                <p class="mx-1">Semester:<select class="form-control mb-1 w-75 ml-1" name="semester" required>
                  <option value="2019/2020 Gasal">2019/2020 Gasal</option>
                  <option value="2019/2020 Genap">2019/2020 Genap</option>
                  <option value="2020/2021 Gasal">2020/2021 Gasal</option>
                  <option value="2020/2021 Genap">2020/2021 Genap</option>
                  <option value="2021/2022 Gasal">2021/2022 Gasal</option>
                  <option value="2021/2022 Genap">2021/2022 Genap</option>
                  <option value="2022/2023 Gasal">2022/2023 Gasal</option>
                  <option value="2022/2023 Genap">2022/2023 Genap</option>
                </select></p>
                <p class="mx-1">SKS: <input class="form-control w-75 ml-1" type="number" value=1 name="jumlah_sks" required></p>
                <button class="btn btn-success" type="submit">Add Matkul</button>
            </div>
        </div>
        <div class="card-body">
            <p> <textarea class="form-control w-100" placeholder="Description of Mata Kuliah" name="deskripsi" required></textarea></p>
        </div>
    </div>
</form>
{% endblock %}

fakhrialdariaskyapp/templates/main/matkul_read.html
{% extends 'base.html' %} {% block content %}
<div class="card text-white bg-success mt-2 mb-2 mx-auto" style="max-width: 50rem;">
    <div class="card-header d-flex justify-content-between">
        <div class="d-flex flex-column">
            <h5 class="my-auto">{{mata_kuliah.nama}}</h5>
            <p class="card-text m-1 mt-2">Ruangan: {{mata_kuliah.ruangan}}</p>
            <p class="card-text m-1">Dibawa Oleh {{mata_kuliah.dosen}}</p>
        </div>
        <div class="d-flex flex-column">
            <p class="mx-1">{{mata_kuliah.semester}}</p>
            <p class="mx-1">{{mata_kuliah.jumlah_sks}} SKS</p>
        </div>
    </div>
    <div class="card-body">
        <p> {{mata_kuliah.deskripsi}} </p>
    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <title>Yusuf Fakhri Aldrian's site
    </title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>



    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://static.fontawesome.com/css/fontawesome-app.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/alda.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'img/django-logo-negative.svg' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block meta %} {% endblock meta %}


</head>

<body>

    {% include 'navbar.html' %}

    <div class="container bg-light-transparent align-self-center container justify-content-center">
        <br><br><br><br>
        <h1 class="text-light">
            Profile
        </h1>

    </div>


    <div class="container justify-content-center">
        <div class="jumbotron bg-muted my-auto .justify-content-center">
            {% block content %} {% endblock content %}
</body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" href="/">
        <img src="{% static 'img/django-logo-negative.svg' %}" height=30px alt=""> Yusuf Fakhri Aldrian
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">


        <a class="navbar-brand" href="#">

        </a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="/">Beranda</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">Profil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/matkuls">Matkul</a>
            </li>
        </ul>

        <ul class="navbar-nav my-2 my-sm-0y">
            <li class="nav-item">
                <a class="nav-link text-light disabled" href="#">Usernamemu</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light disabled" href="#">Emailmu</a>
            </li>
            <li class="nav-item">

                <a class="btn btn-outline-danger" href="/story/logout" role="button">Logout</a>
            </li>
        </ul>

    </div>
</nav>